# Default values for helm
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicaCount: 1
image:
  cregistry: "ghcr.io"
  repository: "svestor"
  app:
    name: "kbot"
    version: "v1"
  # Overrides the image tag whose default is the chart appVersion
  tag: "v1.0.7-15d24c8"
  os: "linux"
  arch: "amd64"
secret:
  tokenName: "TELE_TOKEN"
  name: "kbot-secret"
  tokenKey: "5952812176:AAEKq_MSj02GQCWnddQgN092jMnn5-t9ozA"
securityContext:
  privileged: true
