# Default values for helm
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicaCount: 7
image:
  cregistry: "docker.io"
  repository: "svestor"
  app:
    name: "kbot"
  # Overrides the image tag whose default is the chart appVersion
  tag: "v1.0.7-c5afe96"
  os: "linux"
  arch: "amd64"
app:
  name: "kbot-app"
  version: "v1"
secret:
  tokenName: "TELE_TOKEN"
  name: "kbot-secret"
  tokenKey: "token"
securityContext:
  privileged: true
