# Default values for helm
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicaCount: 1
image:
  cregistry: "ghcr.io"
  repository: "svestor"
  app:
    name: "kbot"
  # Overrides the image tag whose default is the chart appVersion
  tag: "v1.0.7-be1034c"
  os: "linux"
  arch: "amd64"
app:
  name: "kbot-app"
  version: "v1"
secret:
  tokenName: "TELE_TOKEN"
  name: "kbot-secret"
  tokenKey: "NTk1MjgxMjE3NjpBQUdfQ3B3SDFiQ2VWcUN6SHdYTjlTUG9Qb2JTdXJrOHNyWQ=="
securityContext:
  privileged: true
