name: Changed-Files

on: 
  #workflow_dispatch
  push:
    branches: [ "main" ]
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changes
        run: | 
            echo "modified sha is: " ${{ github.event.before }}
            
            echo "all modified files:"
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} 

            if [[ ! $( git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^A' ) ]]; then
               echo "No files were created"
            else
               echo "created files:"
               git diff --name-status ${{ github.event.before }} ${{ github.event.after}} | grep '^A'
            fi

            if [[ ! $( git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^M' ) ]]; then
               echo "No files were updated"
            else
               echo "updated files:"
               git diff --name-status ${{ github.event.before }} ${{ github.event.after}} | grep '^M'
            fi

            if [[ ! $( git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^D' ) ]]; then
               echo "No files were removed"
            else
               echo "removed files:"
               git diff --name-status ${{ github.event.before }} ${{ github.event.after}} | grep '^D'
            fi