name: Changed-Files

on: 
  #workflow_dispatch
  push:
    branches: [ "main" ]
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changes
        run: | 
            echo "modified sha is: " ${{ github.event.before }}
            
            echo "all modified files:"
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} 

            if [[$(git diff --name-status ${{ github.event.before }} ${{ github.event.after }} --exit-code 0) -eq 0]]; then
               echo "No files created."
            else
               git diff --name-status ${{ github.event.before }} ${{ github.event.after}} | grep '^A'
            fi