name: Changed-Files

on: 
  #workflow_dispatch
  push:
    branches: [ "main" ]
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changes
        run: | 
            echo ${{ github.event.before }}
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }}    
