name: Changed-Files

on: 
  #workflow_dispatch
  push:
    branches: [ "main" ]
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changes
        run: | 
            echo "modified sha is: " ${{ github.event.before }}
            
            echo "all modified files: "
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} 

            echo "all created:"
            git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^A'
            
            echo "all removed:"
            git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^D'
            
            echo "all updated:"
            git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^M'   
